### ISSUE TITLE
Initial draft

### ISSUE THREAD

**Issue by szdavid92** [hegyibalint/TDK2017#9]
Let's sketch a draft as early as possible

Determine structure
- chapter
  - title
  - subsections
  - description in two sentences
  - assignee
  - estimated length

**Comment by szdavid92** [comment]
@szarnyasg @hegyibalint

**Comment by szarnyasg** [comment]
Pls make a shared google doc for this

**Comment by hegyibalint** [comment]
https://github.com/hegyibalint/TDK2017/wiki/TDK-TOC contains the TOC, should we add the additional info to that page?

**Comment by szarnyasg** [comment]
I don't think it's necessary to add more info -> feel free to convert this to TeX chapters/sections/etc.
